# ======== DATABASE (POSTGRESQL) ========
# URL нашей БД "taxi_db"
spring.datasource.url=jdbc:postgresql://localhost:5432/taxi_db
spring.datasource.username=postgres
# Укажи свой пароль от Postgres
spring.datasource.password=${DB_PASSWORD:adm}
spring.datasource.driver-class-name=org.postgresql.Driver

# ======== JPA / HIBERNATE ========
# Показывает SQL-запросы в консоли. Удобно для отладки.
spring.jpa.show-sql=true
# Форматирует SQL-запросы в консоли
spring.jpa.properties.hibernate.format_sql=true
# Как ты и просил: "update" сохраняет схему и данные между перезапусками
spring.jpa.hibernate.ddl-auto=update
# Указываем диалект для PostgreSQL, чтобы Hibernate генерировал правильный SQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.taxiapp=DEBUG

app.server.url=https://decorous-tempie-nonsubjugable.ngrok-free.dev


liqpay.public-key=${LIQPAY_PUBLIC_KEY:sandbox_i35513204270}
liqpay.private-key=${LIQPAY_PRIVATE_KEY:sandbox_F92ENukhRWiPhwhAINXmQtAmfQInKOc5jMTvtnoj}

# ======== JWT (JSON Web Token) ========
# Наш секретный ключ. Сделай его длинным и сложным.
jwt.secret=${JWT_SECRET:aVeryLongAndComplexSecretKeyForOurTaxiAppProjectThatIsSecure}
# Время жизни Access токена: 15 минут (900000 миллисекунд)
jwt.expiration=6000000
# Время жизни Refresh токена: 180 дней (15552000000 миллисекунд)
jwt.refresh-expiration=31536000000

# ======== SERVER ========
server.port=8080
# Базовый путь для всех наших API эндпоинтов
server.servlet.context-path=/

spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN


file.upload-dir=${FILE_UPLOAD_DIR:./server-uploads}

# ======== FILE UPLOAD LIMITS (ЛИМИТЫ ЗАГРУЗКИ) ========
# Максимальный размер одного файла (увеличим до 15MB)
spring.servlet.multipart.max-file-size=15MB
# Максимальный размер всего запроса (все фото + JSON) (увеличим до 100MB)
spring.servlet.multipart.max-request-size=100MB

# ======== CORS & WEBSOCKET ========
# Для локальной разработки используем *, для продакшена укажи домены через запятую
# Например: https://my-taxi-admin.com,https://app.taxi.com
app.cors.allowed-origins=*


google.client-id=359347918144-au70gopljkd5gnfheu3kjbhg96qcbek0.apps.googleusercontent.com


# ======== REDIS CONFIG ========
# Для локального запуска оставляем localhost, при деплое в Docker на GCP поменяем на имя контейнера или IP Memorystore
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=6379